name: Build Pathfinding

on:
  push:
    branches: [master]
    tags:
      - "v*"
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup vcpkg using official action
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: "**/vcpkg.json"
          triplet: x64-windows-static

      # 3. Clean build folder (PowerShell)
      - name: Clean build folder
        shell: pwsh
        run: |
          if (Test-Path build) { Remove-Item -Recurse -Force build }

      # 4. Configure CMake
      - name: Configure CMake
        shell: pwsh
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_ROOT\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static

      # 5. Build project
      - name: Build
        run: cmake --build build --config Release

      # 6. Create a release only if push is a tag
      - name: Create Release and Upload EXE
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Pathfinding ${{ github.ref_name }}
          body: Automated build release
          files: build/Release/pathfinding.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
