name: Build Pathfinding

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup vcpkg using official action
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: "**/vcpkg.json"
          triplet: x64-windows-static

      # 3. Clean build folder (PowerShell)
      - name: Clean build folder
        shell: pwsh
        run: |
          if (Test-Path build) { Remove-Item -Recurse -Force build }

      # 4. Configure CMake
      - name: Configure CMake
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ vcpkgRoot }}/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static

      # 5. Build project
      - name: Build
        run: cmake --build build --config Release

<<<<<<< HEAD
      # 7. Create a new release
=======
      # 6. Create a new release (only if push is a tag)
>>>>>>> 233c850 (ispravak)
      - name: Create Release and Upload EXE
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
<<<<<<< HEAD
          tag_name: ${{ github.ref_name }} 
=======
          tag_name: ${{ github.ref_name }}
>>>>>>> 233c850 (ispravak)
          name: Pathfinding ${{ github.ref_name }}
          body: Automated build release
          files: build/Release/pathfinding.exe
        env:
<<<<<<< HEAD
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
=======
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 233c850 (ispravak)
